name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    env:
      KINDE_CLIENT_ID: ${{secrets.KINDE_CLIENT_ID}}
      KINDE_CLIENT_SECRET: ${{secrets.KINDE_CLIENT_SECRET}}
      KINDE_ISSUER_URL: ${{secrets.KINDE_ISSUER_URL}}
      KINDE_SITE_URL: ${{secrets.KINDE_SITE_URL}}
      KINDE_POST_LOGOUT_REDIRECT_URL: ${{secrets.KINDE_POST_LOGOUT_REDIRECT_URL}}
      KINDE_POST_LOGIN_REDIRECT_URL: ${{secrets.KINDE_POST_LOGIN_REDIRECT_URL}}
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      DIRECT_URL: ${{secrets.DIRECT_URL}}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci

      - run: npm run build --if-present

      - name: Change Directory
        run: cd /home/pre777com/htdocs/www.pre777.com/actions-runner/_work/pre777/pre777

      - name: Restart App with pm2 and Pass Environment Variables
        run: |
          cd /home/pre777com/htdocs/www.pre777.com/actions-runner/_work/pre777/pre777
          pm2 restart 0 --update-env
        env:
          KINDE_CLIENT_ID: ${{secrets.KINDE_CLIENT_ID}}
          KINDE_CLIENT_SECRET: ${{secrets.KINDE_CLIENT_SECRET}}
          KINDE_ISSUER_URL: ${{secrets.KINDE_ISSUER_URL}}
          KINDE_SITE_URL: ${{secrets.KINDE_SITE_URL}}
          KINDE_POST_LOGOUT_REDIRECT_URL: ${{secrets.KINDE_POST_LOGOUT_REDIRECT_URL}}
          KINDE_POST_LOGIN_REDIRECT_URL: ${{secrets.KINDE_POST_LOGIN_REDIRECT_URL}}
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          DIRECT_URL: ${{secrets.DIRECT_URL}}
